version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - xray_manager_bot_DB__uri=postgresql://postgres:postgres@db:5432/xray_manager_bot
      - xray_manager_bot_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: xray_manager_bot_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/xray_manager_bot_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=xray_manager_bot, xray_manager_bot_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
